# SPDX-FileCopyrightText: 2021 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  versioning-strategy: increase
  open-pull-requests-limit: 10

# maintained stable branch
- package-ecosystem: npm
  target-branch: stable5
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  versioning-strategy: increase
  open-pull-requests-limit: 10
  ignore:
    # no major updates on stable branches
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]